# Generated by Django 4.1.3 on 2022-11-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('student_mobileno', models.CharField(max_length=20)),
            ],
        ),
    ]
